config/routes.rb
Secc::Application.routes.draw do

  resources :villages

  resources :uploads do
    get :download_dsr,:on=>:member
    get :download_der,:on=>:member
    get :list_revenue_block,:on=>:member
    get :approve,:on=>:member
    get :remarks_dsr,:on=>:member
    get :remarks_der, :on=>:member
  end

  resources :attendances do
    get :approve, :on=>:member
    get :list_revenue_block,:on=>:member
    get :export,:on=>:member
  end

  resources :enumeration_blocks do
    get :list_all,:on=>:member
    get :update_status, :on=>:member
    put :status_update, :on=>:member
    get :status_report, :on=>:collection
    get :status_report_export,:on=>:collection
    get :approve, :on=>:member
    get :remarks, :on=>:member
    get :list_revenue_block,:on=>:member
    get :download_eb_status_report, :on=>:member
  end

  resources :panchayats do
    get :export, :on=>:collection
  end
  resources :users do
    put :csv_import,:on=>:collection
    get :upload,:on=>:collection
    get :export,:on=>:collection
    get :profile,:on=>:member
    get :change_password,:on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
  end

  resources :roles

  resources :revenue_blocks do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :divisions

  resources :districts do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :states do
    get :export, :on=>:collection
  end
  resources :user_sessions

  resources :homes do
    get :manage_revenue_block, :on=>:member
    get :consolidate_report, :on=>:collection
  end

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/state.rb
# Author   : Chaitanya Ram
# Date     : 02022012
#################################
class State < ActiveRecord::Base
  #Relations
  has_many :divisions, :dependent => :destroy
  has_many :districts, :dependent => :destroy
  has_many :revenue_blocks, :dependent => :destroy
  has_many :panchayats, :dependent => :destroy
  has_many :enumeration_blocks, :dependent => :destroy


  #validations
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}
  validates :reference_number, :presence => true, :uniqueness => true, :length => {:maximum => 5}
  validates :reference_name, :presence => true, :uniqueness => true, :length => {:maximum => 10}

  #filters
=begin
  before_create :created_user_id
  def created_user_id
      self.created_by = UserSession.find.user.id
  end
=end

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
  end


end

app/controllers/states_controller.rb
# Controller : States
# Author     : Chaitanya Ram
# Date       : 02022012
#########################################################
class StatesController < ApplicationController
  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show, :edit]

  def index
    @states = State.search(params[:search])
    @state = State.new

  end

  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def edit
    @state = State.find(params[:id])
  end

  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to(states_url, :notice => 'State was successfully created.') }
        format.xml  { render :xml => @state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(states_url) }
      format.xml  { head :ok }
    end
  end
  def export
    @states = State.all
    html = render_to_string :layout => false
    kit = PDFKit.new(html,  :page_size => 'A4',:orientation => 'Landscape')
    send_data(kit.to_pdf, :filename => "States_List"+".pdf", :type => 'application/pdf')

  end
########################################################
private
  def recent_items
    @recent = State.recent
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@state, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:placeholder=>"Enter State Name" %>
        <%= f.input :description %>
        <%= f.input :reference_number, :label => 'Reference Code' %>
        <%= f.input :reference_name, :label => 'Reference Name' %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/states/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent States</h3>
    <% if @recent.blank? %>
        No States Added Yet...
    <% else %>
        <% for state in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to state.name.titleize, state_path(state), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="/states">
        View all States
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/states/_recent_items.html.erb
<% for state in  @recent %>
<li class="" id="recent_state_<%= state.id%>">
    <dt>
        <%=link_to truncate(state.name,:length=>27),"#",:class=>"tipTip1",:title => "View District Details" %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>

app/views/states/edit.html.erb
<% title "VEDAVAAG | SECC | Edit State" %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | SECC | States ',"Edit #{@state.name}") %>
<% end %>
<%= render 'form' %>

app/views/states/export.html.erb
<h5 align="center"> List of States</h5>
<table class="tablesorter1" align="center">
  <thead>
  <tr>
    <th>SNo</th>
    <th>Name</th>
    <th>Reference No</th>
    <th>Reference Name</th>
    <th>Districts</th>
    <th>R-Blocks</th>
    <th>Panchayats</th>
    <th>E-Blocks</th>
  </tr>
  </thead>
  <% i=1 %>
  <% @states.each do |state| %>
      <tr>
        <td><%= i %></td>
        <td><%= state.name.titleize %></td>
        <td><%= "%02d" %state.reference_number %></td>
        <td><%= state.reference_name %></td>
        <td><%= state.districts.size %></td>
        <td><%= state.revenue_blocks.size %></td>
        <td><%= state.panchayats.size %></td>
        <td><%= state.enumeration_blocks.size %></td>
      </tr>
      <% i = i + 1 %>
  <% end %>

</table>

<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #000000;
        font-family: Tahoma, verdana, helvetica, sans-serif;
        font-size: 14px;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #000000;
        text-align: center;
    }
    h5
    {
        font-family: Tahoma, verdana, helvetica, sans-serif;
    }

</style>

app/views/states/index.html.erb
<% title "VEDAVAAG | SECC | States" %>
<h3><%= t :secc%> | <%= t :states %> | <%= t :manage %></h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing States. <br/>
  Along with creating, managing and removing States for Application.
</div>
<%#link_to ((t :create_new) + ' ' + (t :states) ), "#", :class=>'usuallink bold_text', :id=>'add_new' %>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New State'), new_state_path, :class => 'btn-blue' if permitted_to? :create %>
  <%= link_to content_tag(:span, 'Export'), export_states_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
</div>
<!--
<div id="new_form">
  <%#render 'form' %>
</div>
-->
<% if @states.blank? %>
    <div class="error_msg">
      OOPS!.. No States are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>SNo</th>
        <th>Name</th>
        <th>Reference Number</th>
        <th>Reference Name</th>
        <th>Districts</th>
        <th>R-Blocks</th>
        <th>Panchayats</th>
        <th>E-Blocks</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @states.each do |state| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(state.name.titleize,params[:search]) %></td>
            <td><%= "%02d"%state.reference_number %></td>
            <td><%= state.reference_name %></td>
            <td><%= link_to state.districts.size, districts_path, :class => 'tipTipRight', :title => associated_names(state.districts) %></td>
            <td><%= link_to state.revenue_blocks.size, revenue_blocks_path, :class => 'tipTipRight', :title => associated_names(state.revenue_blocks) %></td>
            <td><%= link_to state.panchayats.size, panchayats_path, :class => 'tipTipRight', :title => associated_names(state.panchayats) %></td>
            <td><%= link_to state.enumeration_blocks.size, enumeration_blocks_path, :class => 'tipTipRight', :title => enumeration_block_list(state.enumeration_blocks) %></td>
            <td>
              <%= link_for_show_pop(state) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/states/new.html.erb
<% title "VEDAVAAG | SECC | States " %>
<% content_for :sub_heading do %>
  <%= sub_heading('VEDAVAAG | SECC | States','Create State') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New State' %>
<div class="link_buttons">
 <%=link_to_all(states_path)%>
</div>

app/views/states/show.html.erb
<div id="page_container">
	<div id="page_content">
		<div class="content">
			<h3>VEDAVAAG | SECC | States | View State Details</h3>

<table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
			<tr>
				<th width="20%">Name</th>
				<td><%= @state.name %></td>
			</tr>
			<tr>
				<th width="20%">Reference Code</th>
				<td><%= "%02d"% @state.reference_number %></td>
			</tr>
			<tr>
				<th width="20%">Reference Name</th>
				<td><%= @state.reference_name %></td>
			</tr>
			<tr>
				<th width="20%">Description</th>
				<td><%= @state.description %></td>
			</tr>
</table>
		</div>
	</div>
</div>