config/routes.rb
Secc::Application.routes.draw do

  resources :villages

  resources :uploads do
    get :download_dsr,:on=>:member
    get :download_der,:on=>:member
    get :list_revenue_block,:on=>:member
    get :approve,:on=>:member
    get :remarks_dsr,:on=>:member
    get :remarks_der, :on=>:member
  end

  resources :attendances do
    get :approve, :on=>:member
    get :list_revenue_block,:on=>:member
    get :export,:on=>:member
  end

  resources :enumeration_blocks do
    get :list_all,:on=>:member
    get :update_status, :on=>:member
    put :status_update, :on=>:member
    get :status_report, :on=>:collection
    get :status_report_export,:on=>:collection
    get :approve, :on=>:member
    get :remarks, :on=>:member
    get :list_revenue_block,:on=>:member
    get :download_eb_status_report, :on=>:member
  end

  resources :panchayats do
    get :export, :on=>:collection
  end
  resources :users do
    put :csv_import,:on=>:collection
    get :upload,:on=>:collection
    get :export,:on=>:collection
    get :profile,:on=>:member
    get :change_password,:on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
  end

  resources :roles

  resources :revenue_blocks do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :divisions

  resources :districts do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :states do
    get :export, :on=>:collection
  end
  resources :user_sessions

  resources :homes do
    get :manage_revenue_block, :on=>:member
    get :consolidate_report, :on=>:collection
  end

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/enumeration_block.rb
# Author :Chaitanya
# Date: 15022012
# ##################################################
class EnumerationBlock < ActiveRecord::Base
  #Relation
  belongs_to :panchayat
  belongs_to :user_profile
  belongs_to :revenue_block
  belongs_to :district


  #validations
  #validates :name, :presence => true,  :length => { :maximum => 100
  #validates :panchayat_id, :presence => true
  validates :reference_number, :presence => true, :length => {:maximum => 5} #:uniqueness => true,}

=begin
  #filters
  before_create :created_user_id
  def created_user_id
      self.created_by = UserSession.find.user.id
  end
=end

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(id, query)
      if query
      else
        scoped
      end
    end

    def total_houses(id)
      where(:revenue_block_id => id).sum(:number_of_houses)
    end

    def total_citizens(id)
      where(:revenue_block_id => id).sum(:number_of_citizens)
    end

    def catalog_completed(id)
      where(:catalog_status => "Completed", :revenue_block_id => id)
    end

    def catalog_pending(id)
      where(:catalog_status => "Pending", :revenue_block_id => id)
    end

    def catalog_nys(id)
      where(:catalog_status => "NYS", :revenue_block_id => id)
    end

    def catalog_going(id)
      where(:catalog_status => "Going", :revenue_block_id => id)
    end

    def catalog_no_data(id)
      where(:catalog_status => "No Data", :revenue_block_id => id)
    end

    def enumeration_completed(id)
      where(:enumeration_status => "Completed", :revenue_block_id => id)
    end

    def enumeration_pending(id)
      where(:enumeration_status => "Pending", :revenue_block_id => id)
    end

    def enumeration_nys(id)
      where(:enumeration_status => "NYS", :revenue_block_id => id)
    end

    def enumeration_going(id)
      where(:enumeration_status => "Going", :revenue_block_id => id)
    end

    def enumeration_no_data(id)
      where(:enumeration_status => "No Data", :revenue_block_id => id)
    end

    def enu_nic_upload_completed(id)
      where(:enu_nic_upload_status => "Completed", :revenue_block_id => id)
    end

    def enu_nic_upload_pending(id)
      where(:enu_nic_upload_status => "Pending", :revenue_block_id => id)
    end

    def enu_nic_upload_nys(id)
      where(:enu_nic_upload_status => "NYS", :revenue_block_id => id)
    end

    def enu_nic_upload_going(id)
      where(:enu_nic_upload_status => "Going", :revenue_block_id => id)
    end

    def enu_nic_upload_no_data(id)
      where(:enu_nic_upload_status => "No Data", :revenue_block_id => id)
    end

    def supervising_completed(id)
      where(:supervising_status => "Completed", :revenue_block_id => id)
    end

    def supervising_pending(id)
      where(:supervising_status => "Pending", :revenue_block_id => id)
    end

    def supervising_nys(id)
      where(:supervising_status => "NYS", :revenue_block_id => id)
    end

    def supervising_going(id)
      where(:supervising_status => "Going", :revenue_block_id => id)
    end

    def supervising_no_data (id)
      where(:supervising_status => "No Data", :revenue_block_id => id)
    end

    def super_nic_upload_completed(id)
      where(:super_nic_upload_status => "Completed", :revenue_block_id => id)
    end

    def super_nic_upload_pending(id)
      where(:super_nic_upload_status => "Pending", :revenue_block_id => id)
    end

    def super_nic_upload_nys(id)
      where(:super_nic_upload_status => "NYS", :revenue_block_id => id)
    end

    def super_nic_upload_going(id)
      where(:super_nic_upload_status => "Going", :revenue_block_id => id)
    end

    def super_nic_upload_no_data(id)
      where(:super_nic_upload_status => "No Data", :revenue_block_id => id)
    end

    def draft_list_completed(id)
      where(:draft_list_status => "Completed", :revenue_block_id => id)
    end

    def draft_list_pending(id)
      where(:draft_list_status => "Pending", :revenue_block_id => id)
    end

    def draft_list_nys(id)
      where(:draft_list_status => "NYS", :revenue_block_id => id)
    end

    def draft_list_going(id)
      where(:draft_list_status => "Going", :revenue_block_id => id)
    end

    def draft_list_no_data(id)
      where(:draft_list_status => "No Data", :revenue_block_id => id)
    end

    def draft_list_edit_completed(id)
      where(:draft_list_edit_status => "Completed", :revenue_block_id => id)
    end

    def draft_list_edit_pending(id)
      where(:draft_list_edit_status => "Pending", :revenue_block_id => id)
    end

    def draft_list_edit_nys(id)
      where(:draft_list_edit_status => "NYS", :revenue_block_id => id)
    end

    def draft_list_edit_going (id)
      where(:draft_list_edit_status => "Going", :revenue_block_id => id)
    end

    def draft_list_edit_no_data(id)
      where(:draft_list_edit_status => "No Data", :revenue_block_id => id)
    end

    def final_list_completed (id)
      where(:final_list_status => "Completed", :revenue_block_id => id)
    end

    def final_list_pending(id)
      where(:final_list_status => "Pending", :revenue_block_id => id)
    end

    def final_list_nys (id)
      where(:final_list_status => "NYS", :revenue_block_id => id)
    end

    def final_list_going(id)
      where(:final_list_status => "Going", :revenue_block_id => id)
    end

    def final_list_no_data (id)
      where(:final_list_status => "No Data", :revenue_block_id => id)
    end

=begin
    ##########################################################
    def total_houses_rb
      where(:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id).sum(:number_of_houses)
    end

    def total_citizens_rb
      where(:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id).sum(:number_of_citizens)
    end

    def catalog_completed_rb
      where(:catalog_status => "Completed",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def catalog_pending_rb
      where(:catalog_status => "Pending" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def catalog_nys_rb
      where(:catalog_status => "NYS",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id )
    end
    def catalog_going_rb
      where(:catalog_status => "Going" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def catalog_no_data_rb
      where(:catalog_status => "No Data" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end

    def enumeration_completed_rb
      where(:enumeration_status => "Completed" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enumeration_pending_rb
      where(:enumeration_status => "Pending" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enumeration_nys_rb
      where(:enumeration_status => "NYS" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enumeration_going_rb
      where(:enumeration_status => "Going" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enumeration_no_data_rb
      where(:enumeration_status => "No Data" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end

    def enu_nic_upload_completed_rb
      where(:enu_nic_upload_status => "Completed",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id )
    end
    def enu_nic_upload_pending_rb
      where(:enu_nic_upload_status => "Pending" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enu_nic_upload_nys_rb
      where(:enu_nic_upload_status => "NYS" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enu_nic_upload_going_rb
      where(:enu_nic_upload_status => "Going" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def enu_nic_upload_no_data_rb
      where(:enu_nic_upload_status => "No Data" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def supervising_completed_rb
      where(:supervising_status => "Completed",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id )
    end
    def supervising_pending_rb
      where(:supervising_status => "Pending" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def supervising_nys_rb
      where(:supervising_status => "NYS" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def supervising_going_rb
      where(:supervising_status => "Going" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def supervising_no_data_rb
      where(:supervising_status => "No Data" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def super_nic_upload_completed_rb
      where(:super_nic_upload_status => "Completed" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def super_nic_upload_pending_rb
      where(:super_nic_upload_status => "Pending",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id )
    end
    def super_nic_upload_nys_rb
      where(:super_nic_upload_status => "NYS" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def super_nic_upload_going_rb
      where(:super_nic_upload_status => "Going" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end
    def super_nic_upload_no_data_rb
      where(:super_nic_upload_status => "No Data" ,:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id)
    end

    def draft_list_completed_rb
      where(:draft_list_status => "Completed",:revenue_block_id=>UserSession.find.user.user_profile.revenue_block_id )
    end
    def draft_list_pending_rb

app/controllers/enumeration_blocks_controller.rb
# Author: Chaitanya
# Date: 15022012
#===================================================================
class EnumerationBlocksController < ApplicationController
  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show, :edit,:update_status,:status_report,:remarks]

  def index
    @enumeration_blocks = EnumerationBlock.where(:revenue_block_id => current_user.user_profile.revenue_block_id).paginate(:page =>page, :per_page=>per_page)
    @enumeration_block = EnumerationBlock.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enumeration_blocks }
    end
  end

  def show
    @enumeration_block = EnumerationBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enumeration_block }
    end
  end

  def new
    @enumeration_block = EnumerationBlock.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enumeration_block }
    end
  end

  def edit
    @enumeration_block = EnumerationBlock.find(params[:id])
  end

  def create
    @enumeration_block = EnumerationBlock.new(params[:enumeration_block])
    @enumeration_block.revenue_block_id = current_user.user_profile.revenue_block_id
    @enumeration_block.district_id = current_user.user_profile.district_id
    @enumeration_block.state_id = current_user.user_profile.state_id

    respond_to do |format|
      if @enumeration_block.save
        format.html { redirect_to(enumeration_blocks_url, :notice => 'Enumeration Block Created Successfully.') }
        format.xml  { render :xml => @enumeration_block, :status => :created, :location => @enumeration_block }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enumeration_block.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @enumeration_block = EnumerationBlock.find(params[:id])

    respond_to do |format|
      if @enumeration_block.update_attributes(params[:enumeration_block])
        format.html { redirect_to(@enumeration_block, :notice => 'Enumeration Block was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enumeration_block.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @enumeration_block = EnumerationBlock.find(params[:id])
    @enumeration_block.destroy

    respond_to do |format|
      format.html { redirect_to(enumeration_blocks_url) }
      format.xml  { head :ok }
    end
  end

  def list_all
    @enumeration_blocks = EnumerationBlock.where(:revenue_block_id => params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @enumeration_blocks }
    end
  end
  def list_revenue_block
    @enumeration_blocks = EnumerationBlock.where(:revenue_block_id => params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @enumeration_blocks }
    end
  end
  def update_status
    @enumeration_block = EnumerationBlock.find(params[:id])

  end
  def status_update
    @enumeration_block = EnumerationBlock.find(params[:id])

    respond_to do |format|
      if @enumeration_block.update_attributes(params[:enumeration_block])
        format.html { redirect_to(:back, :notice => 'Enumeration Block Status Successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "update_status" }
        format.xml  { render :xml => @enumeration_block.errors, :status => :unprocessable_entity }
      end
    end
  end
  def status_report
    ## Check Model for Code
  end

  def approve
    @enumeration_block = EnumerationBlock.find(params[:id])
    @enumeration_block.update_attribute('report_status', @enumeration_block.report_status ? false : true)
    respond_to do |format|
      format.js
    end
  end
  def status_report_export
    html = render_to_string :layout => false
    kit = PDFKit.new(html)
    kit.stylesheets << "#{Rails.root}/public/stylesheets/pdf_print.css"
    send_data(kit.to_pdf, :filename => "Status_Report"+".pdf", :type => 'application/pdf')

  end
  def download_eb_status_report
    @enumeration_blocks = EnumerationBlock.where(:revenue_block_id => params[:id])
    html = render_to_string :layout => false
    PDFKit.configure do |config|
      config.default_options = {
          :footer_center => "Page [page] of [toPage]",
          :footer_font_size=>9,
          :footer_left => "Vedavaag Systems Limited"  ,
      }
    end
    kit = PDFKit.new(html,:orientation => 'Landscape', :page_size => 'A4')
    kit.stylesheets << "#{Rails.root}/public/stylesheets/pdf_print.css"
    send_data(kit.to_pdf, :filename => "EB_Status_Report"+".pdf", :type => 'application/pdf')

  end
  def remarks
    @enumeration_block = EnumerationBlock.find(params[:id])
  end
  ########################################################
  private
  def recent_items
    @recent = EnumerationBlock.recent
  end
end

app/helpers/enumeration_blocks_helper.rb
module EnumerationBlocksHelper
end

app/views/enumeration_blocks/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Enumeration Blocks</h3>
    <% if @recent.blank? %>
        No Enumeration Blocks Added Yet...
    <% else %>
        <% for eb in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to eb.reference_number, enumeration_block_path(eb), :class=>'usuallink',:rel=>"facebox" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="/enumeration_blocks">
        View all EB's
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/enumeration_blocks/approve.js.erb
$("#report_status_<%=@enumeration_block.id%>").html("<%=escape_javascript(link_to @enumeration_block.report_status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_enumeration_block_path,:remote=>true)%>");

app/views/enumeration_blocks/index.html.erb
<% title "VEDAVAAG | SECC | Enumeration Blocks" %>
<h3>VEDAVAAG | SECC | Manage | Enumeration Blocks</h3>

<div class="help_text">
  Area for managing Enumeration Blocks. <br/>
  Along with creating, managing Enumeration Blocks for Application. <br/>
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Enumeration Block'), new_enumeration_block_path, :class => 'btn-blue' if permitted_to? :create %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-blue' %>
</div>

<% if @enumeration_blocks.blank? %>
    <div class="error_msg">
      OOPS!.. No Enumeration Blocks are Found for Revenue Block ...!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @enumeration_blocks %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>SNo</th>
        <th>Enumeration No</th>
        <th>Sub EB No</th>
        <th>Houses</th>
        <th>Citizens</th>
        <th>Panchayat</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @enumeration_blocks.each do |eb| %>
          <tr>
            <td><%= i %></td>
            <td><%= eb.reference_number %></td>
            <td><%= eb.sub_enumeration_number %></td>
            <td><%= eb.number_of_houses %></td>
            <td><%= eb.number_of_citizens %></td>
            <td><%= eb.panchayat_id? ? eb.panchayat.name : ""  %></td>
            <td>
              <%= link_for_show_pop(eb) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @enumeration_blocks %> <%= will_paginate @enumeration_blocks, :container => false %>
    </div>
<% end %>

app/views/enumeration_blocks/list_all.html.erb
<% title "VEDAVAAG | SECC | Enumeration Blocks" %>
<h3>VEDAVAAG | SECC | Status Report | Enumeration Blocks</h3>

<div class="help_text">
  * Area for managing Enumeration Blocks Status. <br/>
  * Codes: <b>E-NIC</b> - Enumeration NIC Upload, <b>S-NIC</b> - Supervising NIC Upload Status, <b>Draft</b> - Draft
  Print List,
  <b>Edit</b> - Draft List Modification Status and <b>Final</b> - Final List
</div>
<div id="container">
  <div class="link_buttons">
    <%= link_to content_tag(:span, 'View Consolidated Report'), {:action => :status_report, :controller => :enumeration_blocks, :id => (current_user.user_profile.blank? ? params[:id] : current_user.user_profile.revenue_block_id)}, :class => 'btn-yellow', :rel => "facebox" %>
    <%= link_to content_tag(:span, 'Download Consolidated Report'), {:action => :status_report_export, :controller => :enumeration_blocks, :id => (current_user.user_profile.blank? ? params[:id] : current_user.user_profile.revenue_block_id)}, :class => 'btn-yellow' %>
    <%= link_to content_tag(:span, 'Download Status Report'), "#", :class => 'btn-yellow' %>
    <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
  </div>
</div>
<br/>
<% if @enumeration_blocks.blank? %>
    <div class="error_msg">
      OOPS!.. No Enumeration Blocks are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>SNo</th>
        <th>Status</th>
        <th>Panchayat</th>
        <th>EB#</th>
        <th>Sub EB</th>
        <th>Houses</th>
        <th>Citizens</th>
        <th>Catalog</th>
        <th>Enumeration</th>
        <th>E-NIC</th>
        <th>Supervising</th>
        <th>S-NIC</th>
        <th>Draft</th>
        <th>Edit</th>
        <th>Final</th>
        <th>Remarks</th>
        <% if permitted_to? :update_status %>
            <th>Actions</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @enumeration_blocks.each do |eb| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="report_status_<%= eb.id %>">
                <%= link_to eb.report_status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_enumeration_block_path(eb), :remote => true %>
              </div>
            </td>
            <td><%= eb.panchayat.name + " (" + eb.panchayat.reference_number.to_s + ")" %></td>
            <td><%= eb.reference_number %></td>
            <td><%= eb.sub_enumeration_number %></td>
            <td><%= eb.number_of_houses %></td>
            <td><%= eb.number_of_citizens %></td>
            <td><%= eb.catalog_status %></td>
            <td><%= eb.enumeration_status %></td>
            <td><%= eb.enu_nic_upload_status %></td>
            <td><%= eb.supervising_status %></td>
            <td><%= eb.super_nic_upload_status %></td>
            <td><%= eb.draft_list_status %></td>
            <td><%= eb.draft_list_edit_status %></td>
            <td><%= eb.final_list_status %></td>
            <td><%= eb.remarks? ? (link_to "View", remarks_enumeration_block_path(eb), :rel => "facebox", :class => "usuallink") : '' %></td>
            <% if permitted_to? :update_status %>
                <td>
                  <%= link_to "Update", update_status_enumeration_block_path(eb), :class => 'usuallink bold_text', :rel => "facebox" %>
                </td>
            <% end %>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/enumeration_blocks/list_revenue_block.html.erb
<% title "VEDAVAAG | SECC | Enumeration Blocks" %>
<h3>VEDAVAAG | SECC | Status Report | Enumeration Blocks</h3>

<div class="help_text">
  * Area for managing Enumeration Blocks Status. <br/>
  * Codes: <b>E-NIC</b> - Enumeration NIC Upload, <b>S-NIC</b> - Supervising NIC Upload Status, <b>Draft</b> - Draft
  Print List,
  <b>Edit</b> - Draft List Modification Status and <b>Final</b> - Final List
</div>
<div id="container">
  <div class="link_buttons">
    <%= link_to content_tag(:span, 'View Consolidated Report'), {:action => :status_report, :controller => :enumeration_blocks, :id => (current_user.user_profile.blank? ? params[:id] : current_user.user_profile.revenue_block_id)}, :class => 'btn-yellow', :rel => "facebox" %>
    <%= link_to content_tag(:span, 'Download Consolidated Report'), {:action => :status_report_export, :controller => :enumeration_blocks, :id => (current_user.user_profile.blank? ? params[:id] : current_user.user_profile.revenue_block_id)}, :class => 'btn-yellow' %>
    <%= link_to content_tag(:span, 'Download Status Report'), download_eb_status_report_enumeration_block_path(current_user.user_profile.blank? ? params[:id] : current_user.user_profile.revenue_block_id), :class => 'btn-yellow' %>
    <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
  </div>
</div>
<br/>
<% if @enumeration_blocks.blank? %>
    <div class="error_msg">
      OOPS!.. No Enumeration Blocks are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status</th>
        <!--<th>Panchayat</th>-->
        <th>EB#</th>
        <th>Sub EB</th>
        <th>Houses</th>
        <th>Citizens</th>
        <th>Catalog</th>
        <th>Enumeration</th>
        <th>E-NIC</th>
        <th>Supervising</th>
        <th>S-NIC</th>
        <th>Draft</th>
        <th>Edit</th>
        <th>Final</th>
        <th>Remarks</th>
        <% if permitted_to? :update_status %>
            <th>Actions</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @enumeration_blocks.each do |eb| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="report_status_<%= eb.id %>">
                <%= link_to eb.report_status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_enumeration_block_path(eb), :remote => true %>
              </div>
            </td>
            <!--<td><%# eb.panchayat_id? ? eb.panchayat.name : "" %></td>-->
            <td><%= eb.reference_number %></td>
            <td><%= eb.sub_enumeration_number %></td>
            <td><%= eb.number_of_houses %></td>
            <td><%= eb.number_of_citizens %></td>
            <td><%= eb.catalog_status %></td>
            <td><%= eb.enumeration_status %></td>
            <td><%= eb.enu_nic_upload_status %></td>
            <td><%= eb.supervising_status %></td>
            <td><%= eb.super_nic_upload_status %></td>
            <td><%= eb.draft_list_status %></td>
            <td><%= eb.draft_list_edit_status %></td>
            <td><%= eb.final_list_status %></td>
            <td><%= eb.remarks? ? (link_to "View", remarks_enumeration_block_path(eb), :rel => "facebox", :class => "usuallink") : '' %></td>
            <% if permitted_to? :update_status %>
                <td>
                  <%= link_to "Update", update_status_enumeration_block_path(eb), :class => 'usuallink bold_text', :rel => "facebox" %>
                </td>
            <% end %>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/enumeration_blocks/new.html.erb
<% title "VEDAVAAG | SECC | Enumeration Blocks " %>
<% content_for :sub_heading do %>
  <%= sub_heading('VEDAVAAG | SECC | Enumeration Blocks','Create Enumeration Block') %>
<% end %>
<%= render 'form',:heading => 'Create New Enumeration Block' %>
<div class="link_buttons">
 <%=link_to_all(enumeration_blocks_path)%>
</div>