config/routes.rb
Secc::Application.routes.draw do

  resources :villages

  resources :uploads do
    get :download_dsr,:on=>:member
    get :download_der,:on=>:member
    get :list_revenue_block,:on=>:member
    get :approve,:on=>:member
    get :remarks_dsr,:on=>:member
    get :remarks_der, :on=>:member
  end

  resources :attendances do
    get :approve, :on=>:member
    get :list_revenue_block,:on=>:member
    get :export,:on=>:member
  end

  resources :enumeration_blocks do
    get :list_all,:on=>:member
    get :update_status, :on=>:member
    put :status_update, :on=>:member
    get :status_report, :on=>:collection
    get :status_report_export,:on=>:collection
    get :approve, :on=>:member
    get :remarks, :on=>:member
    get :list_revenue_block,:on=>:member
    get :download_eb_status_report, :on=>:member
  end

  resources :panchayats do
    get :export, :on=>:collection
  end
  resources :users do
    put :csv_import,:on=>:collection
    get :upload,:on=>:collection
    get :export,:on=>:collection
    get :profile,:on=>:member
    get :change_password,:on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
  end

  resources :roles

  resources :revenue_blocks do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :divisions

  resources :districts do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :states do
    get :export, :on=>:collection
  end
  resources :user_sessions

  resources :homes do
    get :manage_revenue_block, :on=>:member
    get :consolidate_report, :on=>:collection
  end

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  #Realtions
  has_many :revenue_blocks

  #Validations
  has_attached_file :dsr
  has_attached_file :der
  validates_attachment_presence :dsr
  validates_attachment_presence :der

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:date.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
  end

end

app/controllers/uploads_controller.rb
# Author: Chaitanya Ram N
# Date : 08032012
####################################################
class UploadsController < ApplicationController
  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show, :edit,:remarks_der,:remarks_dsr]

  def index
    @uploads = Upload.where(:revenue_block_id => current_user.user_profile.revenue_block_id).paginate(:page => page, :per_page => per_page) if has_any_role?(:block_admin,:block_supervisor)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @uploads }
    end
  end

  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @upload }
    end
  end

  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @upload }
    end
  end

  def edit
    @upload = Upload.find(params[:id])
  end

  def create
    @upload = Upload.new(params[:upload])
    @upload.revenue_block_id = current_user.user_profile.revenue_block_id
    @upload.uploaded_by = current_user.id

    respond_to do |format|
      if @upload.save
        format.html { redirect_to(uploads_url, :notice => 'Reports are Uploaded Successfully.') }
        format.xml { render :xml => @upload, :status => :created, :location => @upload }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to(@upload, :notice => 'Upload was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to(uploads_url) }
      format.xml { head :ok }
    end
  end

  def download_dsr
    @upload = Upload.find(params[:id])
    send_file @upload.dsr.path, :type => @upload.dsr_content_type, :disposition => 'inline'

  end

  def download_der
    @upload = Upload.find(params[:id])
    send_file @upload.der.path, :type => @upload.der_content_type, :disposition => 'inline'
  end

  def list_revenue_block
    @uploads = Upload.where(:revenue_block_id => params[:id]).paginate(:page => page, :per_page => per_page)
  end

  def approve
    @upload = Upload.find(params[:id])
    @upload.update_attribute('status', @upload.status ? false : true)
    @upload.update_attribute('approved_by', current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def remarks_dsr
    @upload = Upload.find(params[:id])
  end
  def remarks_der
    @upload = Upload.find(params[:id])
  end
  ########################################################
  private
  def recent_items
    @recent = Upload.recent
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<div class="form-container-1">
  <%= form_for(@upload, :html => {:multipart => true}) do |f| %>
      <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
      </p>
      <fieldset>
        <%= f.error_messages %>
        <div>
          <label for="name">
            Date: <em>*</em>
          </label>
          <%= f.text_field :date,:size=>20,:id=>"date",:value=>Time.now.strftime('%d-%m-%Y') %>
        </div>
        <div>
          <label for="pin">
            Upload Daily Summary Report File: <em>*</em>
          </label>
          <%= f.file_field :dsr,:id=>"dsr"%>
          <script type="text/javascript">
              var dsr = new LiveValidation('dsr', {
                  onlyOnSubmit: true
              });
              dsr.add(Validate.Presence)
          </script>

        </div>
        <div>
          <label for="name">
            Description:
          </label>
          <%= f.text_area :dsr_description, :cols=>20, :rows=>2 %>
        </div>


        <div>
          <label for="pin">
            Upload Data Entry Daily Report File: <em>*</em>
          </label>
          <%= f.file_field :der,:id=>"der" %>
          <script type="text/javascript">
              var der = new LiveValidation('der', {
                  onlyOnSubmit: true
              });
              der.add(Validate.Presence)
          </script>

        </div>
        <div>
          <label for="name">
            Description:
          </label>
          <%= f.text_area :der_description, :cols=>20, :rows=>2 %>
        </div>

        <div class="actions">
          <%= f.submit "Upload", :class=>"btnEdit",:disable_with => 'Please wait...' %>
        </div>
      </fieldset>
  <% end %>
</div>
<script>
    $(function () {
        $("#date").datepicker({dateFormat:'dd-mm-yy', maxDate:0, minDate:-1 });
    });
</script>

app/views/uploads/approve.js.erb
$("#status_<%=@upload.id%>").html("<%=escape_javascript(link_to @upload.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_upload_path,:remote=>true)%>");

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<% title "VEDAVAAG | SECC | Report Upload" %>
<h3>VEDAVAAG | SECC | Report Uploads | Manage</h3>
<div class="help_text">
  Area for managing Daily Summary Report (DSR) and Data Entry Daily Reports (DEDR).
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'Upload Report'), new_upload_path, :class => 'btn-blue' if permitted_to? :create %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-blue' %>
</div>

<% if @uploads.blank? %>
    <div class="error_msg">
      OOPS!.. No Uploaded Reports are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @uploads %>
        </td>
      </tr>
    </table>

    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status</th>
        <th>Date</th>
        <th>Day Summary Report</th>
        <th>DSR Remarks</th>
        <th>Data Entry Report</th>
        <th>DEDR Remarks</th>
        <th>Uploaded</th>
        <th>Approved</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @uploads.each do |upload| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= upload.id %>">
                <%= link_to upload.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_upload_path(upload), :remote => true %>
              </div>

            </td>
            <td><%= upload.date.strftime('%d-%m-%Y') %></td>
            <td><%= link_to "Download", download_dsr_upload_path(upload),:class => 'usuallink bold_text' %></td>
            <td><%= upload.dsr_description? ? (link_to "View","#") : 'N.A' %></td>
            <td><%= link_to "Download", download_der_upload_path(upload),:class => 'usuallink bold_text' %></td>
            <td><%= upload.der_description? ? (link_to "View","#") : 'N.A' %></td>
            <td><%= User.where(:id=>upload.uploaded_by).first.name%></td>
            <td><%= upload.approved_by? ? User.where(:id=> upload.approved_by).first.name : '---' %></td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @uploads %> <%= will_paginate @uploads, :container => false %>
    </div>

<% end %>

app/views/uploads/list_revenue_block.html.erb
<% title "VEDAVAAG | SECC | Report Upload" %>
<h3>VEDAVAAG | SECC | Report Uploads | Manage</h3>
<div class="help_text">
  Area for managing Daily Summary Report (DSR) and Data Entry Daily Reports (DEDR).
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'Upload Report'), new_upload_path, :class => 'btn-blue' if permitted_to? :create %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-blue' %>
</div>

<% if @uploads.blank? %>
    <div class="error_msg">
      OOPS!.. No Uploaded Reports are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @uploads %>
        </td>
      </tr>
    </table>

    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status</th>
        <th>Date</th>
        <th>Day Summary Report</th>
        <th>DSR Remarks</th>
        <th>Data Entry Report</th>
        <th>DEDR Remarks</th>
        <th>Uploaded</th>
        <th>Approved</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @uploads.each do |upload| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= upload.id %>">
                <%= link_to upload.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_upload_path(upload), :remote => true %>
              </div>

            </td>
            <td><%= upload.date.strftime('%d-%m-%Y') %></td>
            <td><%= link_to "Download", download_dsr_upload_path(upload),:class => 'usuallink bold_text' %></td>
            <td><%= upload.dsr_description? ? (link_to "View",remarks_dsr_upload_path(upload),:rel=>"facebox") : 'N.A' %></td>
            <td><%= link_to "Download", download_der_upload_path(upload),:class => 'usuallink bold_text' %></td>
            <td><%= upload.der_description? ? (link_to "View",remarks_der_upload_path(upload),:rel=>"facebox") : 'N.A' %></td>
            <td><%= User.where(:id=>upload.uploaded_by).first.name%></td>
            <td><%= upload.approved_by? ? User.where(:id=> upload.approved_by).first.name : '---' %></td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @uploads %> <%= will_paginate @uploads, :container => false %>
    </div>

<% end %>

app/views/uploads/new.html.erb
<% title "VEDAVAAG | SECC | Report Upload " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | SECC | Report Upload','Upload Report') %>
<% end %>
<%= render 'form',:heading => 'Create New District' %>
<div class="link_buttons">
  <%=link_to_all(uploads_path)%>
</div>

app/views/uploads/remarks_der.html.erb
<% title "VEDAVAAG | SECC | Uploads" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>VEDAVAAG | SECC | Report Uploads | Remarks for Daily Date Entry Report</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Remarks</th>
          <td><%= @upload.der_description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/uploads/remarks_dsr.html.erb
<% title "VEDAVAAG | SECC | Uploads" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>VEDAVAAG | SECC | Report Upload | Daily Summary Report Remarks</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Remarks</th>
          <td><%= @upload.dsr_description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>