config/routes.rb
Secc::Application.routes.draw do

  resources :villages

  resources :uploads do
    get :download_dsr,:on=>:member
    get :download_der,:on=>:member
    get :list_revenue_block,:on=>:member
    get :approve,:on=>:member
    get :remarks_dsr,:on=>:member
    get :remarks_der, :on=>:member
  end

  resources :attendances do
    get :approve, :on=>:member
    get :list_revenue_block,:on=>:member
    get :export,:on=>:member
  end

  resources :enumeration_blocks do
    get :list_all,:on=>:member
    get :update_status, :on=>:member
    put :status_update, :on=>:member
    get :status_report, :on=>:collection
    get :status_report_export,:on=>:collection
    get :approve, :on=>:member
    get :remarks, :on=>:member
    get :list_revenue_block,:on=>:member
    get :download_eb_status_report, :on=>:member
  end

  resources :panchayats do
    get :export, :on=>:collection
  end
  resources :users do
    put :csv_import,:on=>:collection
    get :upload,:on=>:collection
    get :export,:on=>:collection
    get :profile,:on=>:member
    get :change_password,:on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
  end

  resources :roles

  resources :revenue_blocks do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :divisions

  resources :districts do
    get :export, :on=>:collection
    get :approve,:on=>:member
  end
  resources :states do
    get :export, :on=>:collection
  end
  resources :user_sessions

  resources :homes do
    get :manage_revenue_block, :on=>:member
    get :consolidate_report, :on=>:collection
  end

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_block_menu.html.erb
<ul class="page_menu">
    <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage Users" %>
      </li>
      <li>
        <%= link_to 'Panchayat', panchayats_path,:class=>"tipTip1",:title=>"Manage Panchayats" %>
      </li>
      <li>
        <%= link_to 'Enumeration Blocks', enumeration_blocks_path,:class=>"tipTip1",:title=>"Manage E-Blocks" %>
      </li>
    </ul>
  </li>
<!--
  <li><%# tab_heading 'Work' %>
    <ul>
      <li>
        <%#link_to 'Manage Attendance', attendances_path ,:class=>"tipTip1",:title=>"Manage Attendance" %>
      </li>
      <li>
        <%# link_to 'Manage Uploads', uploads_path ,:class=>"tipTip1",:title=>"Manage Uploads" %>
      </li>
    </ul>
  </li>
-->
</ul>

app/views/common/_district_menu.html.erb
<ul class="page_menu">
    <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage Panchayats" %>
      </li>
    </ul>
  </li>
    <li><%= tab_heading 'Work' %>
    <ul>
      <li>
        <%= link_to 'Status Report', list_all_enumeration_blocks_path ,:class=>"tipTip1",:title=>"Status Report of Enumeration Blocks" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_ecil_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'States', states_path,:class=>"tipTip1",:title=>"Manage States" %>
      </li>
      <!--
      <li>
        <%# link_to 'Divisions', divisions_path,:class=>"tipTip",:title=>"Manage Divisions" %>
      </li>
-->
      <li>
        <%= link_to 'Districts', districts_path,:class=>"tipTip1",:title=>"Manage Districts" %>
      </li>
      <li>
        <%= link_to 'Revenue Blocks', revenue_blocks_path,:class=>"tipTip1",:title=>"Manage Revenue Blocks" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_flash_message.html.erb
<div id="flash_messages">
	<% flash.each do |name, msg| %>
	<%= content_tag :div, :id => "flash_#{name}",:class =>"flash_#{name}"  do %>
	<%= msg %>
	<%= content_tag :span, :style => "float: right;" do %>
	<%= link_to_function 'close',:title=>'Close',
	:onclick => "document.getElementById('flash_#{name}').style.display='none'" %>
	<% end %>
	<% end %>
	<% end %>
</div>

app/views/common/_footer.html.erb
<div class="copyright_text">
    <div>
      ©     <%= Time.now.strftime('%Y') %>
  <a href="http://vedavaag.com" target="_blank">Vedavaag</a> Systems Limited. This is site is optimized to Mozilla Firefox, Google Chrome and IE8+ Versions.
    </div>
</div>

app/views/common/_header.html.erb
<div id="page_top">
  <%= link_to image_tag("logo1.png", :border => 0), homes_url %>
  <div id="top_menu">
    <div id="top_m">
      <ul class="top_menu">
        <li>Welcome-
          <% if current_user.user_profile.blank? %>
          <% else %>
              <% if current_user.user_profile.revenue_block_id?%>
              <%= current_user.user_profile.revenue_block.name %> - RBlock -
              <%else%>
              <%end%>
        <% end %>
          <%= current_user.name %>
        </li>
        <li><%= link_to 'Home', homes_url %></li>
        <li><%= link_to 'Profile', profile_user_path(current_user.id) %></li>
        <li>
          <a href="?locale=hi">हिंदी</a> | <a href="?locale=en">English</a>
        </li>
        <li><%= link_to "Sign out", logout_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/common/_import_flash.html.erb
<%flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}",:class =>"flash_#{name}" %>
<%end %>

app/views/common/_manager_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'States', states_path, :class => "tipTip1", :title => "Manage States" %>
      </li>
      <li>
        <%= link_to 'Districts', districts_path, :class => "tipTip1", :title => "Manage Districts" %>
      </li>
      <li>
        <%= link_to 'Revenue Blocks', revenue_blocks_path, :class => "tipTip1", :title => "Manage Revenue Blocks" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_menu.html.erb
<ul class="page_menu">
    <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'States', states_path,:class=>"tipTip1",:title=>"Manage States" %>
      </li>
<!--
      <li>
        <%= link_to 'Divisions', divisions_path,:class=>"tipTip1",:title=>"Manage Divisions" %>
      </li>
-->
      <li>
        <%= link_to 'Districts', districts_path,:class=>"tipTip1",:title=>"Manage Districts" %>
      </li>
      <li>
        <%= link_to 'Revenue Blocks', revenue_blocks_path,:class=>"tipTip1",:title=>"Manage Revenue Blocks" %>
      </li>
      <li>
        <%= link_to 'Roles', roles_path,:class=>"tipTip1",:title=>"Manage Roles" %>
      </li>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage Users" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_search.html.erb
<div class="search" style="">
    <div class="margin">
        <h3>Search</h3>
        <div class="searchbox">
            <%= form_tag(controller_name, :method => 'get') do %>
             <%= hidden_field_tag :id, params[:id] %>
            <%= text_field_tag :search, params[:search], :class => "formTextBox tipTipRight",:size=>20, :title=>"Enter String to Search" %>
            <%= submit_tag 'Go', :disable_with=>'...'%>
            <% end %>
        </div>
    </div>
</div>